  name: Purge jsDelivr cache
  run-name: ${{ github.actor }} is clearing cache in jsDelivr 🚀
  on: [push]
  jobs:
    purge-jsdelivr-cache:
      runs-on: ubuntu-20.04
      steps:
        - uses: gacts/purge-jsdelivr-cache@v1
          with:
            url: |
             https://cdn.jsdelivr.net/gh/jonohall/Shopify-Hide-Unavailable-Options@latest/source.js
             https://cdn.jsdelivr.net/gh/jonohall/Shopify-Hide-Unavailable-Options@latest/source.min.js
